@ECHO OFF
IF "%A7_LOCAL_SETS%" == "1" GOTO A7_P_settings_accepted
SET A7_LOCAL_SETS=1
SET A7_PATH_MINGW=F:/A5/MinGW
SET A7_PATH_GIT=F:/PROGRAMS/GIT/cmd
SET PATH=%PATH%;%A7_PATH_MINGW%/bin;%A7_PATH_MINGW%/msys/1.0/bin;%A7_PATH_GIT%
:A7_P_settings_accepted
ECHO ON
